name: Run Notebooks and Save Outputs

on:
  push:
    branches:
      - main  # Trigger the action on the main branch
      - mb/jb
      - mb/codereview

permissions:
  id-token: write

jobs:
  # Run the notebooks
  run-notebooks:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clear GitHub Action Caches
        run: |
          echo "Clearing caches..."
          sudo rm -rf ~/.cache/pip
          sudo rm -rf executed_notebooks
        if: runner.os != 'Windows'  # Skip sudo on Windows

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install SCT
        shell: bash
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            # Windows-specific installation steps
            echo "Installing SCT on Windows..."
            # Download the Windows installer script
            git clone --depth 1 https://github.com/spinalcordtoolbox/spinalcordtoolbox.git
            # Run the installer script
            ./spinalcordtoolbox/install_sct-win.bat
            # Set SCT_DIR and add SCT to PATH (as instructed by the installer)
            echo "SCT_DIR=C:\path\to\sct" >> $env:GITHUB_ENV
            echo "C:\path\to\sct\bin" >> $env:GITHUB_PATH
          else
            # Linux/macOS installation steps
            echo "Installing SCT on Linux/macOS..."
            git clone --depth 1 https://github.com/spinalcordtoolbox/spinalcordtoolbox.git
            printf 'y\ny\n' | spinalcordtoolbox/install_sct
            # Handle .bashrc modifications for Linux/macOS
            cat ~/.bashrc | grep "export SCT_DIR" | cut -d " " -f 2 >> $GITHUB_ENV
            cat ~/.bashrc | grep "export PATH" | grep -o "/.*" | cut -d ':' -f 1 >> $GITHUB_PATH
          fi

      - name: Verify SCT installation
        run: | 
          # Make sure SCT can be called from within the environment
          sct_check_dependencies

      - name: Run Jupyter Notebooks and build book
        continue-on-error: true  # Allow workflow to continue even if notebook execution fails
        run: jupyter-book build .

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './_build/html'
